# Generated by Django 6.0.7 on 2026-07-14 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anbieter',
            fields=[
                ('anbieter_id', models.AutoField(primary_key=True, serialize=False)),
                ('typ', models.CharField(choices=[('akteur', 'Einzelperson (Akteur)'), ('team', 'Team / Organisationseinheit')], max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_main', models.CharField(blank=True, max_length=50, verbose_name='Telefon 1')),
                ('phone_secondary', models.CharField(blank=True, max_length=50, verbose_name='Telefon 2')),
                ('website', models.URLField(blank=True)),
                ('verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Ausstehend (wartet auf Freigabe)'), ('approved', 'Freigegeben'), ('rejected', 'Abgelehnt')], default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eingereicht_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eingereichte_anbieter', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anbieter',
                'verbose_name_plural': 'Anbieter',
                'db_table': 'anbieter',
            },
        ),
        migrations.CreateModel(
            name='Einsatzgebiet',
            fields=[
                ('gebiet_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('region', models.CharField(blank=True, max_length=255)),
                ('geometry', models.TextField(blank=True, help_text='GeoJSON, falls vorhanden')),
            ],
            options={
                'verbose_name_plural': 'Einsatzgebiete',
                'db_table': 'einsatzgebiet',
            },
        ),
        migrations.CreateModel(
            name='Oberbegriff',
            fields=[
                ('ober_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Oberbegriffe',
                'db_table': 'oberbegriff',
            },
        ),
        migrations.CreateModel(
            name='OperativePSNV',
            fields=[
                ('operative_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Operative PSNV',
                'verbose_name_plural': 'Operative PSNV',
                'db_table': 'operative_psnv',
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('organisation_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('bos_kategorie', models.CharField(blank=True, choices=[('Polizei', 'Polizei'), ('Feuerwehr', 'Feuerwehr'), ('THW', 'THW'), ('BOS-Sonstige', 'BOS - Sonstige')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organisation',
                'verbose_name_plural': 'Organisationen',
                'db_table': 'organisation',
            },
        ),
        migrations.CreateModel(
            name='PSNVAngebot',
            fields=[
                ('angebot_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('dienst_typ', models.CharField(blank=True, choices=[('Psychosoziale_Beratung', 'Psychosoziale Beratung'), ('Soziale_Dienste', 'Soziale Dienste')], max_length=30)),
                ('art_betreuung', models.CharField(blank=True, choices=[('Klinisch', 'Klinisch'), ('Psychotherapeutisch', 'Psychotherapeutisch')], max_length=30)),
                ('liefermodus', models.CharField(blank=True, choices=[('intern', 'Intern (nur eigene Organisation)'), ('extern', 'Extern (für alle registrierten AKI-Akteure sichtbar)'), ('intern und extern', 'Intern und extern')], max_length=20)),
            ],
            options={
                'verbose_name': 'PSNV-Angebot',
                'verbose_name_plural': 'PSNV-Angebote',
                'db_table': 'psnv_angebot',
            },
        ),
        migrations.CreateModel(
            name='Qualifikation',
            fields=[
                ('qual_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Qualifikationen',
                'db_table': 'qualifikation',
            },
        ),
        migrations.CreateModel(
            name='Spezialisierung',
            fields=[
                ('spez_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Spezialisierungen',
                'db_table': 'spezialisierung',
            },
        ),
        migrations.CreateModel(
            name='Sprache',
            fields=[
                ('sprache_id', models.AutoField(primary_key=True, serialize=False)),
                ('iso_code', models.CharField(blank=True, max_length=10)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Sprachen',
                'db_table': 'sprache',
            },
        ),
        migrations.CreateModel(
            name='Stelle',
            fields=[
                ('stelle_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Stellen',
                'db_table': 'stelle',
            },
        ),
        migrations.CreateModel(
            name='Versorgungsphase',
            fields=[
                ('phase_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Versorgungsphasen',
                'db_table': 'versorgungsphase',
            },
        ),
        migrations.CreateModel(
            name='Zielgruppe',
            fields=[
                ('ziel_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('intern_nur', models.BooleanField(default=False)),
                ('extern_nur', models.BooleanField(default=False)),
                ('individuelle_betreuung', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Zielgruppen',
                'db_table': 'zielgruppe',
            },
        ),
        migrations.CreateModel(
            name='Akteur',
            fields=[
                ('anbieter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='psnv.anbieter')),
            ],
            options={
                'verbose_name': 'Akteur (Einzelperson)',
                'verbose_name_plural': 'Akteure (Einzelpersonen)',
                'db_table': 'akteur',
            },
            bases=('psnv.anbieter',),
        ),
        migrations.CreateModel(
            name='AlarmKanal',
            fields=[
                ('kanal_id', models.AutoField(primary_key=True, serialize=False)),
                ('channel_type', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('anbieter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarm_kanaele', to='psnv.anbieter')),
            ],
            options={
                'verbose_name': 'Alarmierungskanal',
                'verbose_name_plural': 'Alarmierungskanäle',
                'db_table': 'alarm_kanal',
            },
        ),
        migrations.CreateModel(
            name='AnbieterEinsatzgebiet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anbieter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psnv.anbieter')),
                ('gebiet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psnv.einsatzgebiet')),
            ],
            options={
                'db_table': 'anbieter_einsatzgebiet',
                'unique_together': {('anbieter', 'gebiet')},
            },
        ),
        migrations.AddField(
            model_name='anbieter',
            name='einsatzgebiete',
            field=models.ManyToManyField(blank=True, related_name='anbieter', through='psnv.AnbieterEinsatzgebiet', to='psnv.einsatzgebiet'),
        ),
        migrations.CreateModel(
            name='Einwilligung',
            fields=[
                ('ein_id', models.AutoField(primary_key=True, serialize=False)),
                ('umfrage', models.BooleanField(default=False, help_text='Einwilligung zur Umfrage-Teilnahme')),
                ('aki_sichtbarkeit', models.BooleanField(default=False, help_text='Einwilligung zur Sichtbarkeit im AKI')),
                ('consent_date', models.DateField(blank=True, null=True)),
                ('anbieter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='einwilligungen', to='psnv.anbieter')),
            ],
            options={
                'verbose_name_plural': 'Einwilligungen',
                'db_table': 'einwilligung',
            },
        ),
        migrations.CreateModel(
            name='Finanzierung',
            fields=[
                ('fin_id', models.AutoField(primary_key=True, serialize=False)),
                ('form', models.CharField(max_length=255)),
                ('note', models.TextField(blank=True)),
                ('anbieter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finanzierungen', to='psnv.anbieter')),
            ],
            options={
                'verbose_name_plural': 'Finanzierungen',
                'db_table': 'finanzierung',
            },
        ),
        migrations.CreateModel(
            name='GrossschadenErfahrung',
            fields=[
                ('erf_id', models.AutoField(primary_key=True, serialize=False)),
                ('einsatz_anzahl', models.PositiveIntegerField(help_text='Anzahl Einsätze in Großschadenslagen')),
                ('anbieter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grossschaden_erfahrungen', to='psnv.anbieter')),
            ],
            options={
                'verbose_name': 'Großschadenslagen-Erfahrung',
                'verbose_name_plural': 'Großschadenslagen-Erfahrungen',
                'db_table': 'grossschaden_erfahrung',
            },
        ),
        migrations.CreateModel(
            name='AnbieterOberbegriff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anbieter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psnv.anbieter')),
                ('ober', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psnv.oberbegriff')),
            ],
            options={
                'db_table': 'anbieter_oberbegriff',
                'unique_together': {('anbieter', 'ober')},
            },
        ),
        migrations.AddField(
            model_name='anbieter',
            name='oberbegriffe',
            field=models.ManyToManyField(blank=True, related_name='anbieter', through='psnv.AnbieterOberbegriff', to='psnv.oberbegriff'),
        ),
        migrations.CreateModel(
            name='AnbieterOperative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anbieter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psnv.anbieter')),
                ('operative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psnv.operativepsnv')),
            ],
            options={
                'db_table': 'anbieter_operative',
                'unique_together': {('anbieter', 'operative')},
            },
        ),
        migrations.AddField(
            model_name='anbieter',
            name='operative_psnv',
            field=models.ManyToManyField(blank=True, related_name='anbieter', through='psnv.AnbieterOperative', to='psnv.operativepsnv'),
        ),
        migrations.CreateModel(
            name='OrganisationStandort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psnv.organisation')),
            ],
            options={
                'db_table': 'organisation_standort',
            },
        ),
        migrations.CreateModel(
            name='AnbieterAngebot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anbieter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psnv.anbieter')),
                ('angebot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psnv.psnvangebot')),
            ],
            options={
                'db_table': 'anbieter_angebot',
                'unique_together': {('anbieter', 'angebot')},
            },
        ),
        migrations.AddField(
            model_name='anbieter',
            name='angebote',
            field=models.ManyToManyField(blank=True, related_name='anbieter', through='psnv.AnbieterAngebot', to='psnv.psnvangebot'),
        ),
        migrations.CreateModel(
            name='AnbieterQualifikation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aggregated', models.BooleanField(default=False, help_text='Angabe gilt aggregiert für das gesamte Team, nicht für eine Einzelperson')),
                ('anbieter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psnv.anbieter')),
                ('qual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psnv.qualifikation')),
            ],
            options={
                'db_table': 'anbieter_qualifikation',
                'unique_together': {('anbieter', 'qual')},
            },
        ),
        migrations.AddField(
            model_name='anbieter',
            name='qualifikationen',
            field=models.ManyToManyField(blank=True, related_name='anbieter', through='psnv.AnbieterQualifikation', to='psnv.qualifikation'),
        ),
        migrations.CreateModel(
            name='AnbieterSpezialisierung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anbieter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psnv.anbieter')),
                ('spez', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psnv.spezialisierung')),
            ],
            options={
                'db_table': 'anbieter_spezialisierung',
                'unique_together': {('anbieter', 'spez')},
            },
        ),
        migrations.AddField(
            model_name='anbieter',
            name='spezialisierungen',
            field=models.ManyToManyField(blank=True, related_name='anbieter', through='psnv.AnbieterSpezialisierung', to='psnv.spezialisierung'),
        ),
        migrations.CreateModel(
            name='AnbieterSprache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anbieter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psnv.anbieter')),
                ('sprache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psnv.sprache')),
            ],
            options={
                'db_table': 'anbieter_sprache',
                'unique_together': {('anbieter', 'sprache')},
            },
        ),
        migrations.AddField(
            model_name='anbieter',
            name='sprachen',
            field=models.ManyToManyField(blank=True, related_name='anbieter', through='psnv.AnbieterSprache', to='psnv.sprache'),
        ),
        migrations.CreateModel(
            name='Standort',
            fields=[
                ('standort_id', models.AutoField(primary_key=True, serialize=False)),
                ('street', models.CharField(blank=True, max_length=255, verbose_name='Straße')),
                ('house_number', models.CharField(blank=True, max_length=20, verbose_name='Hausnummer')),
                ('zip_code', models.CharField(blank=True, max_length=10, verbose_name='PLZ')),
                ('city', models.CharField(blank=True, max_length=255, verbose_name='Ort')),
                ('region', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=255, verbose_name='Bundesland')),
                ('country', models.CharField(default='Germany', max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('location_type', models.CharField(blank=True, choices=[('stationaer', 'Stationär / standortgebunden'), ('regional', 'Regional'), ('bundesweit', 'Bundesweit'), ('andere', 'Andere')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisationen', models.ManyToManyField(blank=True, related_name='standorte', through='psnv.OrganisationStandort', to='psnv.organisation')),
            ],
            options={
                'verbose_name': 'Standort',
                'verbose_name_plural': 'Standorte',
                'db_table': 'standort',
            },
        ),
        migrations.AddField(
            model_name='organisationstandort',
            name='standort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psnv.standort'),
        ),
        migrations.CreateModel(
            name='AnbieterStelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anbieter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psnv.anbieter')),
                ('stelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psnv.stelle')),
            ],
            options={
                'db_table': 'anbieter_stelle',
            },
        ),
        migrations.AddField(
            model_name='anbieter',
            name='stellen',
            field=models.ManyToManyField(blank=True, related_name='anbieter', through='psnv.AnbieterStelle', to='psnv.stelle'),
        ),
        migrations.CreateModel(
            name='Verfuegbarkeit',
            fields=[
                ('verf_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True)),
                ('anbieter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verfuegbarkeiten', to='psnv.anbieter')),
            ],
            options={
                'verbose_name_plural': 'Verfügbarkeiten',
                'db_table': 'verfuegbarkeit',
            },
        ),
        migrations.CreateModel(
            name='AnbieterPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anbieter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psnv.anbieter')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psnv.versorgungsphase')),
            ],
            options={
                'db_table': 'anbieter_phase',
            },
        ),
        migrations.AddField(
            model_name='anbieter',
            name='versorgungsphasen',
            field=models.ManyToManyField(blank=True, related_name='anbieter', through='psnv.AnbieterPhase', to='psnv.versorgungsphase'),
        ),
        migrations.CreateModel(
            name='SpezZielgruppe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spez', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psnv.spezialisierung')),
                ('ziel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psnv.zielgruppe')),
            ],
            options={
                'db_table': 'spez_zielgruppe',
            },
        ),
        migrations.AddField(
            model_name='spezialisierung',
            name='zielgruppen',
            field=models.ManyToManyField(blank=True, related_name='spezialisierungen', through='psnv.SpezZielgruppe', to='psnv.zielgruppe'),
        ),
        migrations.CreateModel(
            name='AkteurOrganisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psnv.organisation')),
                ('akteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psnv.akteur')),
            ],
            options={
                'db_table': 'akteur_organisation',
            },
        ),
        migrations.AddField(
            model_name='akteur',
            name='organisationen',
            field=models.ManyToManyField(blank=True, related_name='mitglieder', through='psnv.AkteurOrganisation', to='psnv.organisation'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('anbieter_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='psnv.anbieter')),
                ('standort', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='psnv.standort')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'db_table': 'team',
            },
            bases=('psnv.anbieter',),
        ),
        migrations.CreateModel(
            name='AkteurTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('akteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psnv.akteur')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psnv.team')),
            ],
            options={
                'db_table': 'akteur_team',
            },
        ),
        migrations.AddField(
            model_name='akteur',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='mitglieder', through='psnv.AkteurTeam', to='psnv.team'),
        ),
        migrations.AddIndex(
            model_name='standort',
            index=models.Index(fields=['region', 'state', 'latitude', 'longitude'], name='standort_region_c576a6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='organisationstandort',
            unique_together={('organisation', 'standort')},
        ),
        migrations.AlterUniqueTogether(
            name='anbieterstelle',
            unique_together={('anbieter', 'stelle')},
        ),
        migrations.AlterUniqueTogether(
            name='anbieterphase',
            unique_together={('anbieter', 'phase')},
        ),
        migrations.AddIndex(
            model_name='anbieter',
            index=models.Index(fields=['name'], name='anbieter_name_2ef5aa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='spezzielgruppe',
            unique_together={('spez', 'ziel')},
        ),
        migrations.AlterUniqueTogether(
            name='akteurorganisation',
            unique_together={('akteur', 'organisation')},
        ),
        migrations.AlterUniqueTogether(
            name='akteurteam',
            unique_together={('akteur', 'team')},
        ),
    ]
